version: '3'

services:
  db:
    image: mysql:latest
    container_name: "mysql-server"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: clinica_odonto
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin_server"
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data: {}
